"""Export 3D building meshes to OBJ + MTL files."""

import os
import re
from datetime import datetime

from .model_builder import BuildingMesh

# Material definitions (pure geometric, no texture maps)
_MTL_CONTENT = """\
# City 3D Model — materials
# Generated by city3dmodels (https://github.com/waholulu/city3dmodels)

newmtl mat_wall
Ka 0.10 0.10 0.10
Kd 0.80 0.80 0.78
Ks 0.00 0.00 0.00
illum 1

newmtl mat_roof
Ka 0.10 0.10 0.10
Kd 0.75 0.55 0.45
Ks 0.00 0.00 0.00
illum 1

newmtl mat_ground
Ka 0.05 0.05 0.05
Kd 0.20 0.20 0.20
Ks 0.00 0.00 0.00
illum 1
"""


def _city_slug(city_name: str) -> str:
    """Convert city name to a safe filename slug."""
    slug = city_name.lower().strip()
    slug = re.sub(r"[^a-z0-9]+", "_", slug)
    return slug.strip("_") or "city"


def export(
    meshes: list[BuildingMesh],
    output_dir: str,
    city_name: str = "city",
    radius_m: float = 2000.0,
    lat: float = 0.0,
    lon: float = 0.0,
) -> tuple[str, str]:
    """
    Write OBJ and MTL files to output_dir.

    Args:
        meshes:     List of BuildingMesh objects to export.
        output_dir: Directory to write files into (created if absent).
        city_name:  Used to derive the output filename slug.
        radius_m:   Radius of the area, embedded in the header comment.
        lat, lon:   City centre coordinates, embedded in the header comment.

    Returns:
        (obj_path, mtl_path) absolute paths to the written files.
    """
    os.makedirs(output_dir, exist_ok=True)

    slug = _city_slug(city_name)
    obj_path = os.path.join(output_dir, f"{slug}.obj")
    mtl_path = os.path.join(output_dir, f"{slug}.mtl")
    mtl_filename = os.path.basename(mtl_path)

    _write_mtl(mtl_path)
    _write_obj(obj_path, mtl_filename, meshes, city_name, radius_m, lat, lon)

    return obj_path, mtl_path


def _write_mtl(mtl_path: str) -> None:
    with open(mtl_path, "w", encoding="utf-8") as f:
        f.write(_MTL_CONTENT)


def _write_obj(
    obj_path: str,
    mtl_filename: str,
    meshes: list[BuildingMesh],
    city_name: str,
    radius_m: float,
    lat: float,
    lon: float,
) -> None:
    timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    total_buildings = len(meshes)

    with open(obj_path, "w", encoding="utf-8") as f:
        # Header
        f.write(f"# City 3D Model — {city_name}\n")
        f.write(f"# Generated: {timestamp}\n")
        f.write(f"# Source: OpenStreetMap contributors (ODbL 1.0)\n")
        f.write(f"# Centre: lat={lat:.6f}, lon={lon:.6f}  |  Radius: {radius_m:.0f} m\n")
        f.write(f"# Scale: 1:10000 (1 OBJ unit = 1 metre)\n")
        f.write(f"# Coordinate system: X=east, Y=north, Z=up  (origin at city centre)\n")
        f.write(f"# Buildings: {total_buildings}\n")
        f.write(f"#\n")
        f.write(f"mtllib {mtl_filename}\n\n")

        global_vertex_offset = 0  # running 0-based count of vertices written so far

        for mesh in meshes:
            if not mesh.vertices or not mesh.faces:
                continue

            f.write(f"g building_{mesh.osm_id}\n")

            # Write vertices for this building
            for x, y, z in mesh.vertices:
                f.write(f"v {x:.4f} {y:.4f} {z:.4f}\n")

            # Write faces, grouped by material
            current_material = None
            for indices, material in mesh.faces:
                if material != current_material:
                    f.write(f"usemtl {material}\n")
                    current_material = material
                # Adjust indices from mesh-local (1-based) to global (1-based)
                global_indices = [idx + global_vertex_offset for idx in indices]
                f.write("f " + " ".join(str(i) for i in global_indices) + "\n")

            global_vertex_offset += len(mesh.vertices)
            f.write("\n")
